### ISSUE TITLE
diseño de objeto 3d

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-dream-team1-0#1]
[PRACTICA OBJETO EN 3D EN BLENDER.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-dream-team1-0/files/11123819/PRACTICA.OBJETO.EN.3D.EN.BLENDER.pdf)

**Comment by carlos-chrs** [comment]
Muy Bien Hecho.
17/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
